#!/usr/bin/env bash

set -e

# === VARIABLES DECLARATION === #

DEFAULT_CONFIG_PREFIX="dotfiles"
CONFIG_SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

declare -A DOTBOT_PLUGINS
DOTBOT_PLUGINS=(["packages"]="dotbot-yay" ["sudo"]="dotbot-sudo")

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# === FUNCTION DECLARATION === #

function installDotfiles {
        if [ -f "$(dirname pwd)/dotfiles.conf.yaml" ]; then
            "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "dotfiles${CONFIG_SUFFIX}" 
        else 
            echo "dotfiles.conf.yaml does not exist. Please make sure it's in your dotfiles' root repository and try again."
        fi
}

function installSudoDotfiles {
        if [ -f "$(dirname pwd)/sudodotfiles.conf.yaml" ]; then
            "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "sudodotfiles${CONFIG_SUFFIX}" \
            --plugin-dir "dotbot-sudo"
        else 
            echo "sudodotfiles.conf.yaml does not exist. Please make sure it's in your dotfiles' root repository and try again."
        fi
}

function installPackages {
        if [ -f "$(dirname pwd)/packages.conf.yaml" ]; then
            "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "packages${CONFIG_SUFFIX}" \
            --plugin-dir "dotbot-yay"
        else 
            echo "packages.conf.yaml does not exist. Please make sure it's in your dotfiles' root repository and try again."
        fi
}

# === MAIN === #
main() {

    tput setaf 3; echo -e "Welcome to Freshgiammi's custom dotbot installer. \n" 
    tput sgr0;

    while true; do
        read -p "Do you wish to install dotfiles (Y/N)? " yn
        case $yn in
            [Yy]* ) installDotfiles; break;;
            [Nn]* ) break;;
            * ) echo "Please answer yes or no.";;
        esac
    done

        while true; do
        read -p "Do you wish to install dotfiles (with sudo) (Y/N)? " yn
        case $yn in
            [Yy]* ) installSudoDotfiles; break;;
            [Nn]* ) break;;
            * ) echo "Please answer yes or no.";;
        esac
    done

    while true; do
        read -p "Do you wish to install programs with yay (Y/N)? " yn
        case $yn in
            [Yy]* ) installPackages; break;;
            [Nn]* ) break;;
            * ) echo "Please answer yes or no.";;
        esac
    done

}

main